create extension if not exists pgcrypto;

create table if not exists public.retail_space_listings (
  id uuid primary key default gen_random_uuid(),
  source text not null,
  source_tier text not null default 'public-web',
  external_id text not null,
  canonical_key text not null unique,
  url text not null,
  title text not null,
  property_name text,
  address text,
  city text not null default 'Seattle',
  state text not null default 'WA',
  zip text,
  neighborhood text,
  suite text,
  latitude double precision,
  longitude double precision,
  property_type text not null default 'Commercial',
  min_sf integer,
  max_sf integer,
  available_sf integer,
  asking_rate_raw text,
  base_rate_psf_year numeric,
  nnn_psf_year numeric,
  estimated_monthly numeric,
  rate_confidence text not null default 'unknown',
  lease_type text not null default 'unknown',
  available_date text,
  features text[] not null default '{}',
  image_url text,
  description text,
  broker text,
  company text,
  quality_score integer not null default 0,
  quality_reasons text[] not null default '{}',
  status text not null default 'active' check (status in ('active', 'stale', 'expired')),
  first_seen timestamptz not null default now(),
  last_seen timestamptz not null default now(),
  source_updated_at timestamptz,
  missed_runs integer not null default 0,
  raw jsonb not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists retail_space_listings_status_idx
  on public.retail_space_listings (status, last_seen desc);
create index if not exists retail_space_listings_source_idx
  on public.retail_space_listings (source, status);
create index if not exists retail_space_listings_address_idx
  on public.retail_space_listings (lower(address));

create table if not exists public.retail_space_source_runs (
  id bigint generated by default as identity primary key,
  source text not null,
  tier text not null,
  status text not null,
  record_count integer not null default 0,
  attempted_at timestamptz not null default now(),
  completed_at timestamptz not null default now(),
  message text not null default ''
);

create index if not exists retail_space_source_runs_latest_idx
  on public.retail_space_source_runs (source, attempted_at desc);

create table if not exists public.retail_space_refresh_leases (
  id text primary key,
  owner text not null,
  expires_at timestamptz not null,
  updated_at timestamptz not null default now()
);

create or replace function public.acquire_retail_space_refresh_lease(
  p_owner text,
  p_lease_seconds integer default 300
) returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  affected integer;
begin
  insert into public.retail_space_refresh_leases (id, owner, expires_at, updated_at)
  values ('inventory', p_owner, now() + make_interval(secs => greatest(30, p_lease_seconds)), now())
  on conflict (id) do update
    set owner = excluded.owner,
        expires_at = excluded.expires_at,
        updated_at = now()
    where public.retail_space_refresh_leases.expires_at < now()
       or public.retail_space_refresh_leases.owner = p_owner;
  get diagnostics affected = row_count;
  return affected = 1;
end;
$$;

create or replace function public.release_retail_space_refresh_lease(
  p_owner text
) returns void
language sql
security definer
set search_path = public
as $$
  delete from public.retail_space_refresh_leases
  where id = 'inventory' and owner = p_owner;
$$;

alter table public.retail_space_listings enable row level security;
alter table public.retail_space_source_runs enable row level security;
alter table public.retail_space_refresh_leases enable row level security;

revoke all on public.retail_space_listings from anon, authenticated;
revoke all on public.retail_space_source_runs from anon, authenticated;
revoke all on public.retail_space_refresh_leases from anon, authenticated;
revoke all on function public.acquire_retail_space_refresh_lease(text, integer) from anon, authenticated;
revoke all on function public.release_retail_space_refresh_lease(text) from anon, authenticated;
